Initial commit GEC documentation
ALLUOS/ALLUOS.github.io pull request #57
Opened 2021-08-12 13:31 UTC by mheyen

Person | Total Word Count | Section(s)
-- | -- | --
Polina  |  1058  |  Motivation + Tools and Models (GECToR + Fine-tuning and Datasets)
Jannik  |  687  | Implementation (Grammatical Error Detection Pipeline ) + Outlook and Limitations
Malte  |  917  |  Tools and Models (LanguageTool) + Implementation (Grammar Feedback and Passing the Task)
Paribartan  |    | Goal and Scope

2021-08-13 11:03 UTC, pariyashu approved these changes

2021-08-13 16:02 UTC, polina-tsvilodub requested changes
Thank you for creating the text! From my view, the text can be added as soon as the following little issue is resolved:
* in the Goal & Scope part, the feedback texts are not completely up to date. Please see my comments in the Google doc which provide the links where the current texts can be found
* as stated in the Google doc comment, I think the list of common errors that we actually count should be added in that part, too

Thanks for all your work @mheyen !

2021-08-14 16:56 UTC, polina-tsvilodub approved these changes

2021-08-14 18:17 UTC, EmmaZanoli requested changes
This review addresses solely broken links and images. Review of the content will follow in our upcoming review phase starting on Monday ☺️ 

Every link has been fixed, except for the one about completion metrics, which Polina is currently working on 😊

2021-08-14 18:17 UTC, EmmaZanoli commented on _posts/2021-02-01-NLP.md
> +We used the dataset created for the [sentence correction task](link) specifically to assess the False Positive rate of the tools since a hand-checked ground truth was given for these sentences. The r
```suggestion
We used the dataset created for the [sentence correction task]({{ "" | absolute_url }}/2021/03/03/sentence-correction.html) specifically to assess the False Positive rate of the tools since a hand-checked ground truth was given for these sentences. The results of this evaluation can be seen below:
```

2021-08-14 18:17 UTC, EmmaZanoli commented on _posts/2021-02-01-NLP.md
> +To assure this, we ran an evaluation script and tested the tool on three datasets (see [Fine-tuning and datasets](Fine-tuning and datasets)).
```suggestion
To assure this, we ran an evaluation script and tested the tool on three datasets (see [Fine-tuning and Datasets](#fine-tuning-and-datasets)). 
```

2021-08-14 18:17 UTC, EmmaZanoli commented on _posts/2021-02-01-NLP.md
> +The first tool we tested and evaluated for our task is the python library `language_tool_python` (https://pypi.org/project/language-tool-python/) which is a Python wrapper for LanguageTool. LanguageT
```suggestion
The first tool we tested and evaluated for our task is the python library `language_tool_python` ([https://pypi.org/project/language-tool-python/](https://pypi.org/project/language-tool-python/)) which is a Python wrapper for LanguageTool. LanguageTool (LT) is an open-source spelling and grammar checker used in OpenOffice (see the project home page at https://languagetool.org for more information and source code). It was originally developed by Daniel Naber during his diploma work and is currently maintained by him and an open source community (Naber, 2003). 
```

2021-08-14 18:17 UTC, EmmaZanoli commented on _posts/2021-02-01-NLP.md
> +Another reason for adding GEC to the discussion task is the improvement of the completion metric for this task. That is, in line with the [escape-room](link to storytelling) framing of the app, users
```suggestion
Another reason for adding GEC to the discussion task is the improvement of the completion metric for this task. That is, in line with the [escape-room]({{ "" | absolute_url }}/2021/01/03/storytelling.html) framing of the app, users’ performance is linked to getting pieces of the code in order to complete the mission. Previously, the performance was only evaluated quantitatively, i.e., by setting a threshold on the minimal number of words users need to produce in order to pass the task. We deem that adding a qualitative evaluation of the contributions to the completion metric improves the accuracy and is advantageous from a learning experience perspective. Therefore, we integrate a score computed via our GEC tools into the updated [completion metric](Implementation) of the discussion task. Finally, our integration of GEC tools can potentially be of use in other parts of the app in the future.
```

2021-08-14 18:17 UTC, EmmaZanoli commented on _posts/2021-02-01-NLP.md
> +The discussion task offers a suitable framework for actively learning and practicing grammar because in this task, users actively produce language, as opposed to focusing on language comprehension in
```suggestion
The discussion task offers a suitable framework for actively learning and practicing grammar because in this task, users actively produce language, as opposed to focusing on language comprehension in [other tasks]({{ "" | absolute_url }}/#three). To that end, we include diverse feedback on the users’ contributions both after each round of the discussion and at the end of the task.
```

2021-08-14 18:17 UTC, EmmaZanoli commented on _posts/2021-02-01-NLP.md
> +Learning to correctly apply grammatical structures in written language is an important and often difficult task for English learners. Therefore, during this semester, grammatical error correction (GE
```suggestion
Learning to correctly apply grammatical structures in written language is an important and often difficult task for English learners. Therefore, during this semester, grammatical error correction (GEC) was introduced in Escapeling in order to help learners improve their grammar skills. More specifically, state-of-the-art [NLP-tools for GEC](#tools-and-models) were employed in the [discussion task]({{ "" | absolute_url }}/2021/03/02/discussion.html).
```

2021-08-14 18:17 UTC, EmmaZanoli commented on _posts/2021-02-01-NLP.md
> +![](../assets/images/acc-both-final.png)
```suggestion
<img src="{{ "" | relative_url }}/assets/images/acc-both-final.png" alt="" class="center">
```

2021-08-14 18:17 UTC, EmmaZanoli commented on _posts/2021-02-01-NLP.md
> +![](../assets/images/intermediate_feedback_screenshot.jpg)
```suggestion
<img src="{{ "" | relative_url }}/assets/images/intermediate_feedback_screenshot.jpg" alt="" class="center">
```

2021-08-14 18:17 UTC, EmmaZanoli commented on _posts/2021-02-01-NLP.md
> +![](../assets/images/final_feedback_screenshot.jpg)
```suggestion
<img src="{{ "" | relative_url }}/assets/images/final_feedback_screenshot.jpg" alt="" class="center">
```

2021-08-14 18:17 UTC, EmmaZanoli commented on _posts/2021-02-01-NLP.md
> +Naber, D. (2003). A rule-based style and grammar checker (Diplomarbeit, Universität Bielefeld). http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.148.6882&rep=rep1&type=pdf
```suggestion
Naber, D. (2003). A rule-based style and grammar checker (Diplomarbeit, Universität Bielefeld). [http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.148.6882&rep=rep1&type=pdf](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.148.6882&rep=rep1&type=pdf)
```

2021-08-14 18:17 UTC, EmmaZanoli commented on _posts/2021-02-01-NLP.md
> +The group passes the task if they meet two requirements. First, each user has to reach a minimum user score in at least two of the three discussion rounds, which is currently set to 5. The second con
```suggestion
The group passes the task if they meet two requirements. First, each user has to reach a minimum user score in at least two of the three discussion rounds, which is currently set to 5. The second condition is that the group reaches a group threshold together, which is divided into three different levels. The group passes the task at an intermediate level if the score is 5-10; at a good level if the score is 10-15; and at a very good level if the score is at least 15. These conditions are checked in the `is_correct` function in `discussion.py`. The function returns the group level which aligns with the newly developed [storytelling features]({{ "" | absolute_url }}/2021/01/03/storytelling.html) which requires each task to provide one failure and three possible pass stages. 
```

2021-08-15 16:08 UTC, EmmaZanoli approved these changes

2021-08-20 10:40 UTC, veraKl approved these changes
All in all, your documentation part is really very well written and nice to read! It is very well understandable. 

The onliest part that wasn’t clear to me was the beginning of the GECToR part. I think it would be good to take one dedicated spot in your texts, maybe at the Fine-Tuning and Datasets section, where you summarize the advantages and disadvantages of each tool and conclude with your decision to combine them. Then you could leave this part out of the GECToR section. Or you already elaborate on the pros and cons of of each tool in their respective section and then draw your conclusion at one spot in your texts. I feel like the strategy behind this has been a little mixed up.

Nevertheless, you did a really good job!

I know that I marked some spelling mistakes in a section that doesn't belong to you @polina-tsvilodub , but I was reading the whole part between your text, too, to make sure your parts fit in the whole context.

2021-08-20 10:40 UTC, veraKl commented on _posts/2021-02-01-NLP.md
> +
> the users’ contributions

I am not sure if this really is wrong, but it kinda looks unusual… I tried DeepL which suggested:
on user contributions

2021-08-20 10:40 UTC, veraKl commented on _posts/2021-02-01-NLP.md
> +
> users’ performance

It also looks kinda unusual, I would write something like:
the performance of users 
The user performance
the users performance

2021-08-20 10:40 UTC, veraKl commented on _posts/2021-02-01-NLP.md
> +If no common mistakes were made, the bot provides the following feedback at the end of the task: "I did not notice any recurring gramamtical mistakes during the discussion. Good job!"
> that model don’t always provide

doesn't

> any recurring gramamtical mistakes

grammatical

2021-08-20 10:40 UTC, veraKl commented on _posts/2021-02-01-NLP.md
> +
> in grammatical sense

I think 'in a grammatical sense' would be correct

2021-08-20 10:40 UTC, veraKl commented on _posts/2021-02-01-NLP.md
> +
> We decided to chain two models 

which models? Why did you decide to chain them? I feel a little overwhelmed with the first sentence. 

Maybe changing the order and describing the problem first and then elaborating on GECToR could help:
As described above, LT is quite reliable at catching certain types of errors, but misses other kinds of errors, resulting in a lower accuracy at detecting all errors. In order to solve this problem, we are using two different …models…….
In order to achieve a higher error detection accuracy, we decided to additionally use GECToR, an open-source pretrained model published by grammarly (Omelianchuk et al., 2020). It consists of….

Maybe it also makes sense to only describe GECToR here and put the part where you describe the problem with LT at the beginning of “Fine-tuning and Datasets, because you already have a wrap up sentence there which models you choose and why.

2021-08-20 10:40 UTC, veraKl commented on _posts/2021-02-01-NLP.md
> +
> The model consists of a transformer-based sequence tagging encoder with two linear layers on top (Vaswani et al., 2017). The encoder applies error corrections by making token-level transformations of the erroneous input text.

I personally would have some questions about this part because I do not understand all the terms that are used but I think that Thelen is familiar with these terms 😊

> That is, off-the-shelf GECToR is not ideal for identifying the types of errors made by users because no error IDs are available. Using the model requires storing the frozen checkpoints (~500MB) and performing inference via a local API (~3GB).

Then why are you using it? What is GECToR good at?

2021-08-20 10:40 UTC, veraKl commented on _posts/2021-02-01-NLP.md
> +
>  LT and GECToR remained as the two final candidate tools for our use case, among different approaches to GEC proposed by the NLP community

I thought you were using two different models + GECToR. So one of these models is LT and which one is the other one? Maybe I am confusing models and tools.

2021-08-22 15:06 UTC, KristinaSig commented on _posts/2021-02-01-NLP.md
> +
•	the “Goal and Scope” section is overall nicely written, giving details and clear justifications for the decisions taken along the way, limitations, possible extensions of the implementation – well done! 😊
•	a small stylistic suggestion: sometimes the same words occur a lot in a relatively short text span (eg. “users” in the first paragraph), which makes the text a bit cumbersome. Maybe try using more synonyms, pronouns or passives to say the same message with a more variety of words, it makes the text more enjoyable for the brain to read 😊 
•	it may be a good idea to give a little more detail on why/how specifically the types of mistakes, which are to be tracked by the model, were picked. Also, in this section only 5 types of mistakes are listed, but in the implementation, a list of 20 is provided. Are these just some examples? Or have they later been narrowed down to just these 5? It isn’t clear to me from the text.
•	section within lines 48-52 seems a bit repetitive. I think it would also make sense to change the order of the paragraph/main points a bit – to start with line 50-51 which gives reasons for picking only a few types of mistakes, then follow by 48-49 which explains what feedback is given to these mistakes. This is also the order which you use in the previous sentence and I’d say it is more intuitive to stick to it rather than jump back and forth.

2021-08-23 05:38 UTC, polina-tsvilodub commented on _posts/2021-02-01-NLP.md
> +
Thanks for pointing out the confusion. We use two tools (= models)  in total, i.e., LT + GECToR. We will definitely try to make the text more clear regarding that.

2021-08-29 16:26 UTC, EmmaZanoli approved these changes

2021-08-29 16:27 UTC, merged