Implementation
ALLUOS/ALLUOS.github.io pull request #65
Opened 2021-08-15 20:10 UTC by estherchevalier

Author: Esther
Word Count: 914
Sections: Implementation process incl. workflow, code conventions, and improved documentation

2021-08-23 14:45 UTC, mheyen commented on _posts/2021-04-02-implementation.md
> +Following the third and final discussion round, two polls will be presented using reply keyboards and used along with the dictionaries by the `is_correct(self)` method to determine whether the task w
I believe this will be updated by the PR for the NLP task, as we removed the evaluation polls from the discussion task completely.

2021-08-23 15:03 UTC, mheyen requested changes
Great work! 
I think you explained the motivation and technical aspects of the debug mode very well! 
I only have some minor typos and missing commas to bother you with ;D

I also liked the extent to which you explained things in detail and to which you stayed more general :)

2021-08-29 09:47 UTC, EmmaZanoli commented on _posts/2021-04-02-implementation.md
> +Following the third and final discussion round, two polls will be presented using reply keyboards and used along with the dictionaries by the `is_correct(self)` method to determine whether the task w
Hi @mheyen, the discussion task has changed significantly since the work of the NLP task force, as you rightly point out. The description of this task (both in terms of design and implementation) is going to be shifted to its own page (see [this PR)](https://github.com/ALLUOS/ALLUOS.github.io/pull/58). Afterwards, I will remove the outdated content on this page :)

2021-08-29 10:28 UTC, mheyen commented on _posts/2021-04-02-implementation.md
> +The study project team this semester consisted mostly of team members who are new to the project. This was the case especially for the implementation team. This yielded a number of different problems
"... of different problems: The team ..." 
After a colon, "The" should be capitalized, right? 

I agree with Frederik that "the team will describe" sounds a bit weird. Maybe, "we will describe" ?

I think it should be "workflows" (plural).

"the team settled for" -> I'd rather say "we decided on" .

2021-08-29 10:28 UTC, mheyen commented on _posts/2021-04-02-implementation.md
> +Initially, the documentation provided enough information about how to use and start the bot locally. Additionally, the documentation was focussed on the design choices and decisions that were made in
maybe "decisions that were made in the _second_ semester" ?

2021-08-29 10:28 UTC, mheyen commented on _posts/2021-04-02-implementation.md
> +It was decided to create the same kind of documentation for the three task handlers: the discussion task handler, the vocabulary description task handler and the sentence correction task handler. Sin
same comment as Frederik: 
What does "every state is mentioned with an individual within the diagram" mean?

2021-08-29 10:28 UTC, mheyen commented on _posts/2021-04-02-implementation.md
> +During the familiarization with the project’s implementation, it was noticed that the previous developers did not follow some important principles of clean coding. For example, it was  noted that man
"This" should be capitalized after a colon.

2021-08-29 11:29 UTC, EmmaZanoli commented on _posts/2021-04-02-implementation.md
> +During the familiarization with the project’s implementation, it was noticed that the previous developers did not follow some important principles of clean coding. For example, it was  noted that man
Hi @mheyen, I'm a little confused by this 😅 I have to admit that I've never encountered this punctuation convention in any of the scientific papers I've read over the last few years. A [quick google search](https://www.grammarly.com/blog/capitalization-after-colons/) informs me that what you mention is a preference suggested by _some_ style guides, but not universally adopted. For consistency with the rest of the documentation, where such words are not capitalised, I would suggest leaving it as it is 😊

2021-08-29 11:35 UTC, mheyen commented on _posts/2021-04-02-implementation.md
> +During the familiarization with the project’s implementation, it was noticed that the previous developers did not follow some important principles of clean coding. For example, it was  noted that man
You are right, apparently the rules are not as strict in English as I've thought 😅

2021-08-29 14:04 UTC, estherchevalier commented on _posts/2021-04-02-implementation.md
> +It was decided to create the same kind of documentation for the three task handlers: the discussion task handler, the vocabulary description task handler and the sentence correction task handler. Sin
I forgot a word, I hope it's more readable now

2021-08-29 14:08 UTC, mheyen approved these changes

2021-08-29 16:34 UTC, EmmaZanoli approved these changes

2021-08-29 18:27 UTC, merged